#!/usr/bin/env python3
"""Plot Table 2 validation metrics from table2_summary.csv."""

from __future__ import annotations

import argparse
import csv
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np


METRICS = ["BP", "P90", "D90", "D20"]


def read_rows(path: Path) -> list[dict[str, str]]:
    with path.open(newline="", encoding="utf-8") as handle:
        return list(csv.DictReader(handle))


def plot_positions(rows: list[dict[str, str]], output: Path) -> None:
    cases = []
    for row in rows:
        case = f"{row['material']} {row['energy_MeV']}"
        if case not in cases:
            cases.append(case)

    fig, axes = plt.subplots(2, 2, figsize=(12.5, 7.2), sharey=False)
    axes = axes.ravel()
    x = np.arange(len(METRICS))
    width = 0.36

    for ax, case in zip(axes, cases):
        case_rows = [r for r in rows if f"{r['material']} {r['energy_MeV']}" == case]
        paper = [float(next(r for r in case_rows if r["metric"] == m)["paper_table2_cm"]) for m in METRICS]
        gpu = [float(next(r for r in case_rows if r["metric"] == m)["gpu_cm"]) for m in METRICS]

        ax.bar(x - width / 2, paper, width, label="Paper Table 2", color="#4c566a")
        ax.bar(x + width / 2, gpu, width, label="GPU solver", color="#2a9d8f")
        ax.set_title(case)
        ax.set_xticks(x, METRICS)
        ax.set_ylabel("Depth (cm)")
        ax.grid(axis="y", alpha=0.25)

    axes[0].legend(loc="best")
    fig.suptitle("Table 2 Position Metrics: Paper vs GPU Solver")
    fig.tight_layout()
    fig.savefig(output, dpi=220)
    plt.close(fig)


def plot_relative_error(rows: list[dict[str, str]], output: Path) -> None:
    cases = []
    for row in rows:
        case = f"{row['material']} {row['energy_MeV']}"
        if case not in cases:
            cases.append(case)

    fig, ax = plt.subplots(figsize=(12.5, 5.2))
    x = np.arange(len(cases))
    width = 0.18
    colors = ["#2a9d8f", "#e76f51", "#6a4c93", "#8a9a5b"]

    for idx, metric in enumerate(METRICS):
        values = []
        for case in cases:
            row = next(
                r
                for r in rows
                if f"{r['material']} {r['energy_MeV']}" == case and r["metric"] == metric
            )
            values.append(float(row["rel_diff_percent"]))
        ax.bar(x + (idx - 1.5) * width, values, width, label=metric, color=colors[idx])

    ax.axhline(0.0, color="black", linewidth=0.8)
    ax.axhline(1.0, color="0.55", linewidth=0.8, linestyle="--")
    ax.axhline(-1.0, color="0.55", linewidth=0.8, linestyle="--")
    ax.set_xticks(x, cases)
    ax.set_ylabel("Relative difference (%)")
    ax.set_title("Table 2 Relative Differences: GPU Solver vs Paper")
    ax.grid(axis="y", alpha=0.25)
    ax.legend(ncol=4, loc="upper left")
    fig.tight_layout()
    fig.savefig(output, dpi=220)
    plt.close(fig)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--input",
        type=Path,
        default=Path("results/table2_validation/table2_summary.csv"),
        help="CSV generated by scripts/table2_summary.py",
    )
    parser.add_argument(
        "--outdir",
        type=Path,
        default=Path("results/table2_validation"),
        help="Directory for output plots",
    )
    args = parser.parse_args()

    rows = read_rows(args.input)
    args.outdir.mkdir(parents=True, exist_ok=True)
    positions = args.outdir / "table2_positions.png"
    relerr = args.outdir / "table2_relative_error.png"

    plot_positions(rows, positions)
    plot_relative_error(rows, relerr)
    print(f"wrote {positions}")
    print(f"wrote {relerr}")


if __name__ == "__main__":
    main()
